name: Deploy to Aliyun ECS

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 构建前端
      - name: Build Frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

      # 构建后端
      - name: Build Backend
        run: |
          cd backend
          npm install --legacy-peer-deps
          npm run build

      # 部署到阿里云
      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            # 创建必要的目录
            mkdir -p /home/projects/portfolio/frontend/dist
            
            # 清理旧文件
            rm -rf /home/projects/portfolio/frontend/dist/*
            
            # 复制新构建的文件
            cd /home/projects/portfolio/frontend
            npm install --legacy-peer-deps
            npm run build
            
            # 确保 nginx 有权限访问
            sudo chown -R www-data:www-data /home/projects/portfolio/frontend/dist
            
            # 重启 nginx
            sudo systemctl reload nginx
