name: Deploy to Aliyun ECS

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 构建前端
      - name: Build Frontend
        run: |
          cd frontend
          npm install --legacy-peer-deps
          npm run build

      # 构建后端
      - name: Build Backend
        run: |
          cd backend
          npm install --legacy-peer-deps
          npm run build

      # 部署到阿里云
      - name: Deploy to Aliyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/home/projects/portfolio/frontend/dist"
          strip_components: 2

      # 设置权限和重启 nginx
      - name: Setup permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /home/projects/portfolio
            sudo systemctl reload nginx
